### ISSUE TITLE
username and password for enter to dashboare

### ISSUE THREAD

**Issue by sabashaeedi77** [JsonDeveloper/dante-gui#5]
Hello dear I need default credential for entering to dashboard,I use seeder to create test data but I could not cany help me

**Comment by JsonDeveloper** [comment]
The password is set to the .env file: APP_PASSWORD

**Comment by sabashaeedi77** [comment]
Thank you mr Json  I know that password set to. env
but where is the user name

**Comment by JsonDeveloper** [comment]
> Thank you mr Json I know that password set to. env but where is the user name
To log in to the admin panel, only a password is used (without a username or e-mail)
